config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show

  end

  def new
    @pin = current_user.pins.create
  end

  def create
    @pin = current_user.pins.create(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated!"
    else
      render "edit"
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="nav navbar navbar-default">
  <div class="container">
    <div class="navbar-brand"><%= link_to "Pin Board", root_path %>
        <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Pin", new_pin_path %></li>
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
       <% else %>
       <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
      </ul>
          <% end %>
    </div>
  </div>
</div>
<div class="container">
<% flash.each do |name,msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { multipart: true }) do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
     <h2><%= pluralize(@pin.errors.count, "error") %> prevented this Pin from saving</h2>
        <ul>
          <% @pin.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, input_html: { class: "form-control" } %>
    </div>


     <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>

<%= render "form" %>

<%= link_to "Cancel", @pin %>

app/views/pins/index.html.erb
<% @pins.each do |pin| %>
    <h2><%= link_to pin.title, pin %></h2>
<% end %>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Form</h1>

<%= render "form" %>

<%= link_to "Back", root_path %>

</div>

app/views/pins/show.html.erb
<h1><%= @pin.title %></h1>
<p><%= @pin.description %></p>
<p>Submitted by <%= @pin.user.email %></p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_pin_path %>
<%= link_to "Delete", @pin, method: :delete, data: { confirm: "Are you sure? " } %>